import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Generates text content using the Google Gemini API (using the stable gemini-1.5-flash model).
 * @param {string} prompt - The user prompt to send.
 * @param {string} [systemInstruction] - Optional instruction to define the persona or style of the model.
 * @returns {Promise<string|null>} - The text generated by Gemini or null if an error or missing key occurs.
 */
export const generateAIResponse = async (prompt, systemInstruction = "") => {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("Gemini Warning: GEMINI_API_KEY environment variable is not defined. AI feature deactivated.");
    return null;
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({
      model: "gemini-1.5-flash",
      systemInstruction: systemInstruction || undefined,
    });

    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error("Gemini API Error occurred:", error.message || error);
    return null;
  }
};
